### ISSUE TITLE
Tool Head Documentation provides wrong connector in description.

### ISSUE THREAD

**Issue by lee7670** [SBMSpec/SBM-Spec#7]
Tool Head documentation Lists 40 pin MOLEX 71660-7040 as connector, but "For Software Engineers" Lists the Feedstock Canister 14 pin MOLEX 15-24-7143 as the connector further down the page.

**Comment by imjasondunn** [comment]
@lee7670 thanks for noticing the error in the "For Software Engineers" description. It has been fixed to reflect the MOLEX 71660-7040 connector used in the tool head interface.
